### ISSUE TITLE
Wenlin ABC Dictionary (Simplified Chinese)

### ISSUE THREAD

**Issue by rduwjjnh** [MarvNC/yomichan-dictionaries#28]
I compiled Wenlin ABC dictionary from their wiki version here https://wenlin.co/wow/Project:Ci (it's free but you need to sign up and "buy" it https://wenlinshangdian.com/).

[ABC汉英大词典.zip](https://github.com/MarvNC/yomichan-dictionaries/files/12071570/ABC.zip)

Maybe the formatting can be improved, I'm not familiar with what features Yomichan dictionaries can have. Feel free to do whatever with it.

![配](https://github.com/MarvNC/yomichan-dictionaries/assets/79216500/5e80a325-2ec5-4fbf-876b-32b833e02ab8)

**Comment by MarvNC** [comment]
Thanks for the contribution! Will add this to the main repo with the index.json changed for more info.
[[ZH] Wenlin ABC.zip](https://github.com/MarvNC/yomichan-dictionaries/files/12074644/ZH.Wenlin.ABC.zip)
