### ISSUE TITLE
Not able to import dictionaries other than JMDict

### ISSUE THREAD

**Issue by KublaiKhan64** [MarvNC/yomichan-dictionaries#32]
When trying to import any of the dictionaries I get the following error and nothing imports. 

Error: Dictionary has invalid data in 'term_bank_1.json' for value 'dictionary[0][5][1].type', validated against 'schema.additionalItems.items[5].oneOf[1].properties': 0 oneOf schemas matched

Tried this with jmdict extra, New Saitou Japanese-English Dictionary, and both pixiv dictionaries and they all error out.

**Comment by MarvNC** [comment]
Please check that you are on the latest version of Yomichan or Yomitan/Yomibaba - this is a known problem as Firefox's addon store has an outdated version for some reason.
