### ISSUE TITLE
Simplified Hanzi Dictionary Download Links Broken

### ISSUE THREAD

**Issue by shinthor** [MarvNC/yomichan-dictionaries#55]
The links in Mandarin terms section for Simplified versions of 汉语大词典 and  两岸词典 point to discord cdn links that are broken.
These are the links in question:

> 
> **Simplified Chinese Versions**
> 
> Michel converted some of the above dictionaries to simplified Chinese.
> 
> - **[Download `汉语大词典`](https://cdn.discordapp.com/attachments/1102744354222776471/1122247530286166187/hanyudacidian.zip)**
>   - The Hanyu Da Cidian is the most comprehensive Chinese dictionary, comparable to the Oxford
>     English Dictionary.
> - **[Download `两岸词典`](https://cdn.discordapp.com/attachments/1102744354222776471/1122247339965419610/cross-straits.zip)**
>   - The Cross-Straits dictionary is a small mainland dictionary focusing on contemporary usage and
>     the differences between Taiwan and Mainland Chinese.
> 
Are these available elsewhere?

**Comment by MarvNC** [comment]
I'll get these fixed when I have time to update the repo, thanks for letting me know. In the meantime, these should both be available within the Google Drive "Dictionary Collection" I have [linked at the top.](https://github.com/MarvNC/yomichan-dictionaries?tab=readme-ov-file#dictionary-collection)

**Comment by anadventcalendar** [comment]
any update on the Cross Straits dictionary download link? looking for the traditional character one if possible.
