### ISSUE TITLE
Add monolingual English dictionaries

### ISSUE THREAD

**Issue by emanuelps2708** [MarvNC/yomichan-dictionaries#59]
Hi Marv, I found that Seth made a monolingual English dictionary from olad (Oxford Advanced Learner's Dictionary) it has ipa and two options, one with only definitions and other with also example sentences, the link is https://discord.com/channels/1171709317343346789/1180231433571283015/1211581296107851787
Images from the oald-extra dictionary
![image](https://github.com/MarvNC/yomichan-dictionaries/assets/147004033/9315290a-b7d3-47c8-bfba-365ec324b447) 
![image](https://github.com/MarvNC/yomichan-dictionaries/assets/147004033/e5a9ec49-f527-403d-ac09-bd14699e9443)

There's also a google drive with some monolingual English dictionaries made by Umbrella including MacMillan, New Oxford American Dictionary, Cambridge, Longman, Wordset, and a frequency from FLT the link is https://drive.google.com/drive/folders/1APj14ap2yMv0WZvSCEGJq9jfMUpZy6Ao?usp=sharing and the discord message with more info https://discord.com/channels/1171709317343346789/1171709317867655200/1193788026980151327

**Comment by MarvNC** [comment]
Sorry for the delay, I was busy and this issue slipped by my radar.

I'm not in that discord linked, can you copy over the relevant information? I'll add the google drive for now.

**Comment by emanuelps2708** [comment]
Don't worrry Marv you must have been very busy, here is the information shared on the discord server:

"Here's the OALD dictionary I've been working on.
Don't just import the zip. You need to extract it and read the instructions.
Let me know if there are any issues. Enjoy." Message from seth on the Discord Server. 

There is a Yezichak version but I think linking only the Yomitan one would be ok.
[oald-release-yomitan.zip](https://github.com/MarvNC/yomichan-dictionaries/files/14957647/oald-release-yomitan.zip)

"I made Macmillan and New Oxford American Dictionary.
Macmillan now has IPA before definition rather than definition only that I posted yesterday. 
New Oxford American Dictionary has some minor errors in format but it's okay to read or make anki cards.
Frequency_FLT i convert from json file on https://docs.freelanguagetools.org/resources.html (now it don't find it, i downloaded one year ago. you can access this link for more dictionaries in many formats)" Message from Umbrella on the discord server.

**Comment by MarvNC** [comment]
Should all be added.

**Comment by emanuelps2708** [comment]
Thank you Marv ;). I'd suggest to add this message to the OLAD dictionary: 
"Here's the OALD dictionary I've been working on.
Don't just import the zip. You need to extract it and read the instructions."

The reason is because if someone just downloads the dictionary and tries to import it into yomitan it will not work.

**Comment by MarvNC** [comment]
Okay, done
