### ISSUE TITLE
Add Vicon dictionaries

### ISSUE THREAD

**Issue by emanuelps2708** [MarvNC/yomichan-dictionaries#60]
Hi Marv, I found some migaku dictionaries that were converted into yomitan format from _Target Language > English_ and  from _English > Different languages_. The dictionaries data comes from [lingoes](http://www.lingoes.net/en/dictionary/index.html). It includes Arabic, French, German, Greek, Italian, Latin, Russian, Portuguese, Korean, Hebrew, Spanish and English, I put all of them in one of my Proton Drive(alternative to Google Drive) accounts, the link is https://drive.proton.me/urls/3RY82EBQ2M#s7QNTK6lZKtZ

**Comment by emanuelps2708** [comment]
I also included some frequency lists from open subs the link with them is: https://drive.proton.me/urls/X00PZRWG0R#O4eczudoY4Rn
![image](https://github.com/MarvNC/yomichan-dictionaries/assets/147004033/56c62a27-0b21-4017-bee4-a65be18f075d)

**Comment by MarvNC** [comment]
Should all be added.
