### ISSUE TITLE
Add Aurelio dictionary (Portuguese)

### ISSUE THREAD

**Issue by emanuelps2708** [MarvNC/yomichan-dictionaries#62]
[Aurelio.zip](https://github.com/MarvNC/yomichan-dictionaries/files/15145512/Aurelio.zip)

Portuguese monolingual dictionary made by Michel

![image](https://github.com/MarvNC/yomichan-dictionaries/assets/147004033/d63dfc29-aafd-405b-8df2-70c224411931)

**Comment by MarvNC** [comment]
Sorry for the delay, I forgot about this lol
